apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bna-website-pvc
  namespace: bna-website
spec:
  storageClassName: longhorn-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
