project:
  type: website
  output-dir: ../site

lang: en

website:
  title: "Bell & Associates"
  search: false
  navbar:
    title: "<img src='/images/logo.png' alt='Company Logo' style='height:40px;'>"
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
      - href: services.qmd
        text: Services
      - href: portfolio.qmd
        text: Portfolio
      - href: map.qmd
        text: Project Map
      - href: witness.qmd
        text: Expert Witness
      - href: contact.qmd
        text: Contact Us
  page-navigation: true

format:
  html:
    title-block-banner: false
    anchor-sections: false
    search: false
    theme:
      - cosmo
      - brand
    css: styles/index.css
    toc: true
execute:
  enabled: true

metadata-files:
  - _quarto.yml
