---
title: "Bell & Associates"
subtitle: "We know the box"
title-block-banner: images/banner.jpg
format:
    html:
        toc: false
---

Bell & Associates, Inc. is a consulting firm specializing in the financial and
operational analysis of integrated solid waste management. Founded in 2003 by a
licensed Certified Public Accountant, our primary purpose is to serve the
waste/recycling needs of state and local governmental agencies, municipalities,
and tribal communities. Located in Camas, Washington, our client base of public
and private companies extends from Washington to New York and from Alaska to
Florida. Bell & Associates has completed over 600 waste and recycling projects
since its inception, with a primary focus on the economics of the waste and
recycling industry.

Our areas of expertise include:

* waste industry systems and operational analysis
* rate review and rate setting
* compliance services
* alternative fuels
* financial auditing
* long-term planning
* program analysis
* project implementation
* franchise procurement
* training and outreach

# Web Accessibility Statement

Bell & Associates, Inc. tries to deliver a broadly accessible user experience.
There may be features that are not fully accessible due to errors or oversight.
Our ongoing efforts to improve the website includes updating the features to
allow better accessibility.

If you encounter accessibility issues while using our site, please inform us
via the [github issues page for the website](https://github.com/bellandassociates/website/issues).
